/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 paperPlaneAnimation.glb
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/paperPlaneAnimation.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature" position={[-0.23, 0.66, -2.74]} rotation={[-Math.PI / 2, 0, 0]}>
          <primitive object={nodes.Bone} />
          <skinnedMesh name="PaperPlane_Banner" geometry={nodes.PaperPlane_Banner.geometry} material={nodes.PaperPlane_Banner.material} skeleton={nodes.PaperPlane_Banner.skeleton} />
        </group>
        <mesh name="Leafs" geometry={nodes.Leafs.geometry} material={materials.Foliage} rotation={[Math.PI / 2, 0, 0]} />
        <mesh name="Trunks" geometry={nodes.Trunks.geometry} material={materials.Trunk} rotation={[Math.PI / 2, 0, 0]} />
        <mesh name="Grass" geometry={nodes.Grass.geometry} material={materials.Grass} rotation={[Math.PI / 2, 0, 0]} />
        <mesh name="Rocks" geometry={nodes.Rocks.geometry} material={materials.Rocks} rotation={[Math.PI / 2, 0, 0]} />
        <mesh name="P0_Walls" geometry={nodes.P0_Walls.geometry} material={materials.P0_Wall} rotation={[Math.PI / 2, 0, 0]} />
        <mesh name="P0_Roof" geometry={nodes.P0_Roof.geometry} material={materials.P0_Roof} rotation={[Math.PI / 2, 0, 0]} />
        <mesh name="P1_Blocks" geometry={nodes.P1_Blocks.geometry} material={materials.P1_Blocks} rotation={[Math.PI / 2, 0, 0]} />
        <mesh name="PaperPlane" geometry={nodes.PaperPlane.geometry} material={nodes.PaperPlane.material} rotation={[Math.PI / 2, 0, 0]} />
        <mesh name="P2" geometry={nodes.P2.geometry} material={materials.P0_Roof} rotation={[Math.PI / 2, 0, 0]} />
        <mesh name="Prop_Cabin" geometry={nodes.Prop_Cabin.geometry} material={materials.P1_Blocks} rotation={[Math.PI / 2, 0, 0]} />
        <mesh name="Prop_Doors" geometry={nodes.Prop_Doors.geometry} material={materials.P0_Roof} rotation={[Math.PI / 2, 0, 0]} />
      </group>
    </group>
  )
}

useGLTF.preload('/paperPlaneAnimation.glb')
