/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 a.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function A(props) {
  const { nodes, materials } = useGLTF('/assets/gl/a.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]}>
        <mesh castShadow receiveShadow geometry={nodes.Object_1.geometry} material={materials['Material_2.001']} />
        <mesh castShadow receiveShadow geometry={nodes.Object_3.geometry} material={materials['Material_2.001']} />
        <mesh castShadow receiveShadow geometry={nodes.Object_4.geometry} material={materials['Material_2.001']} />
        <mesh castShadow receiveShadow geometry={nodes.Object_5.geometry} material={materials['Material_2.001']} />
        <mesh castShadow receiveShadow geometry={nodes.Object_6.geometry} material={materials['Material_2.001']} />
        <mesh castShadow receiveShadow geometry={nodes.Object_7.geometry} material={materials['Material_2.001']} />
      </group>
    </group>
  )
}

useGLTF.preload('/a.glb')
