/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 b.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function B(props) {
  const { nodes, materials } = useGLTF('/assets/gl/b.glb')
  return (
    <group {...props} dispose={null} scale ={0.1}>
      <group rotation={[Math.PI / 2, 0, 0]} >
        <mesh castShadow receiveShadow geometry={nodes.Object_1.geometry} material={nodes.Object_1.material} />
        <mesh castShadow receiveShadow geometry={nodes.Object_3.geometry} material={nodes.Object_3.material} />
        <mesh castShadow receiveShadow geometry={nodes.Object_4.geometry} material={nodes.Object_4.material} />
        <mesh castShadow receiveShadow geometry={nodes.Object_5.geometry} material={nodes.Object_5.material} />
        <mesh castShadow receiveShadow geometry={nodes.Object_6.geometry} material={nodes.Object_6.material} />
        <mesh castShadow receiveShadow geometry={nodes.Object_7.geometry} material={nodes.Object_7.material} />
      </group>
    </group>
  )
}

useGLTF.preload('/b.glb')
