/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 p0.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function P0(props) {
  const { nodes, materials } = useGLTF('/assets/gl/p0.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]} scale={1}>
        <mesh geometry={nodes.Object_1.geometry} material={materials.Plaster} />
        <mesh geometry={nodes.Object_2.geometry} material={materials.Plaster} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.po_Roof} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.po_Roof} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.p0_Wall} />
      </group>
    </group>
  )
}

useGLTF.preload('/p0.glb')
