/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 TRY.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Try(props) {
  const { nodes, materials } = useGLTF('assets/gl//TRY.glb')
  return (
    <group  {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.Plane.geometry} material={nodes.Plane.material} scale={[10, 5, 10]} />
      <mesh castShadow receiveShadow geometry={nodes.TRY.geometry} material={nodes.TRY.material} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/TRY.glb')
